{"name": "Test for change name", "status": "failed", "statusDetails": {"message": "AssertionError: Dont have this row", "trace": "self = <test_exe.TestExe object at 0xffff7e004f10>\n\n    @allure.title(\"Test for change name\")\n    def test_create_marker_and_change_name_marker(self):\n        self.login_page().open()\n        self.login_page().login()\n        self.menu().settings.open_setting_market()\n        self.markers_pages().open_create()\n        self.markers_pages().create.choose_enable()\n        self.markers_pages().create.fill_name(\"berlin\")\n        self.markers_pages().create.fill_configuration(\"babu\")\n        self.markers_pages().create.fill_market_type(\"Fortex\")\n        self.markers_pages().create.choose_save_to_csv_file()\n        self.markers_pages().create.choose_save_to_log_file()\n        self.markers_pages().create.click_create()\n        self.markers_pages().refresh_page()\n        self.markers_pages().find_row_by_username(\"berlin\")\n        self.markers_pages().click_edit_row_by_username(\"berlin\")\n        self.markers_pages().edit.fill_default_configuration()\n        self.markers_pages().edit.click_yes()\n        self.markers_pages().edit.fill_configuration(\"OneZero\")\n        self.markers_pages().edit.fill_name(\"pagoda\")\n        self.markers_pages().edit.find_save()\n        self.markers_pages().edit.click_save()\n        self.markers_pages().refresh_page()\n>       self.markers_pages().find_row_by_username(\"pagoda\")\n\ntests/test_exe.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.markers_page.page.MarkersPage object at 0xffff7df47810>\nusername = 'pagoda'\n\n    def find_row_by_username(self, username):\n        for i, row in enumerate(self._rows, start=1):\n            if username in self.get_row_content(i):\n                assert True  # нашли — тест проходит\n                return\n>       assert False, \"Dont have this row\"  # не нашли — тест падает\nE       AssertionError: Dont have this row\n\npages/markers_page/page.py:73: AssertionError"}, "attachments": [{"name": 1749520635.9355154, "source": "3b82e297-289f-47f0-a9ac-08b11bcaf7a3-attachment.png", "type": "image/png"}], "start": 1749520644944, "stop": 1749520657160, "uuid": "e2b5b363-803f-49fc-82df-aa61b2879482", "historyId": "f8de49c9b1fe105f7b7d48335c053509", "testCaseId": "f8de49c9b1fe105f7b7d48335c053509", "fullName": "tests.test_exe.TestExe#test_create_marker_and_change_name_marker", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_exe"}, {"name": "subSuite", "value": "TestExe"}, {"name": "host", "value": "a4fb8756a6ac"}, {"name": "thread", "value": "9-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_exe"}]}